@baseUrl = http://127.0.0.1:5000/api

### get profile
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc3NDUzMDc1MCwianRpIjoiYTUyN2RkNWQtNjM4Mi00ZDQ4LWI1MGQtNjJmNWQ1OTM2Y2Y0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjUiLCJuYmYiOjE3NzQ1MzA3NTAsImV4cCI6MTc3NDUzMTY1MH0.L9ZlZUEByhInUiqooS7DodDLIs02Tz5ibcORkgx5eEg
GET {{baseUrl}}/profile
Authorization: Bearer {{token}}