"""create user table

Revision ID: 2354876fedd9
Revises: 
Create Date: 2026-03-31 12:11:34.813592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2354876fedd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False, comment='User ID'),
    sa.Column('username', sa.String(length=80), nullable=False, comment='Username'),
    sa.Column('email', sa.String(length=120), nullable=False, comment='Email'),
    sa.Column('auth_provider', sa.String(length=50), nullable=True, comment='local or google'),
    sa.Column('password_hash', sa.Text(), nullable=True, comment='Password Hash'),
    sa.Column('sub', sa.String(length=255), nullable=True, comment='Google ID'),
    sa.Column('picture', sa.String(length=500), nullable=True, comment='Avatar URL From Google'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Created At'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Updated At'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='Last Login At'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('sub'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
